apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        - name: chromadb
          image: alaasalmo/chromadb:0.0.0.1
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: chroma-storage
              mountPath: /app/chroma-db
      volumes:
        - name: chroma-storage
          persistentVolumeClaim:
            claimName: chromadb-pvc
