apiVersion: v1
kind: Service
metadata:
  name: chromadb-service-internal
spec:
  type: ClusterIP
  selector:
    app: chromadb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      