apiVersion: v1
kind: PersistentVolume
metadata:
  name: chromadb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/chromadb  # Path inside Minikube VM
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

