apiVersion: v1
kind: PersistentVolume
metadata:
  name: ragpython-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/rag/script"